# The name of the workflow.
name: CI/CD Pipeline for Finance Tracker

# Run the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Verify build output  # ✅ Debugging Step
        run: ls -R frontend/.next  

      - name: Upload build artifact
        uses: actions/upload-artifact@v4  # ✅ Ensure v4 is used
        with:
          name: frontend-build
          path: frontend/.next  # ✅ Ensure this path is correct

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4  # ✅ Ensure v4 is used
        with:
          name: frontend-build
          path: frontend/.next  # ✅ Ensure the same path is used

      - name: Verify downloaded artifact  # ✅ Debugging Step
        run: ls -R frontend/.next  

      - name: Deploy frontend to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
