name: CI/CD Pipeline for Spend Smart

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies of frontend
        run: |
          cd frontend
          npm install

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy frontend to Vercel
        run: vercel --yes --token ${{ secrets.VERCEL_TOKEN }}
